### ISSUE TITLE
v2.8.1  in supermarket contains bin/ and test/ files - please re-upload without

### ISSUE THREAD

**Issue by stefanwb** [adamsb6/s3_file#103]
I get this message while trying to freeze this cookbook:

```=== Cookbook Compare errors found ===
The source cookbook contains more files than your upload:
 - bin/s3_crypto
 - test/fixtures/cookbooks/s3_file_test/README.md
 - test/fixtures/cookbooks/s3_file_test/metadata.rb
 - test/fixtures/cookbooks/s3_file_test/recipes/default.rb
 - test/integration/default/serverspec/default_spec.rb
 - test/integration/default/serverspec/spec_helper.rb

Source: https://supermarket.chef.io/api/v1/cookbooks/s3_file/versions/2.8.1/download
```

Solution is re-uploading this cookbook without the files mentioned in `chefignore`

**Comment by joekiller** [comment]
Well that didn't fix it either. Seems to be a tooling issue https://github.com/chef/chef/issues/2994

Will have to look at this a little later.

**Comment by joekiller** [comment]
Seems to ignore the `chefignore` file if you are using the cookbook-path switch ie:

    knife cookbook site share s3_file --cookbook-path $(pwd) --dry-run

had to copy the `cheignore`into the parent directory.

**Comment by joekiller** [comment]
Try 2.8.3
