### ISSUE TITLE
Update from version 2.7 -> 2.81 breaks no_proxy functionality for IAM profile discovery

### ISSUE THREAD

**Issue by ChrisPetr0** [adamsb6/s3_file#104]
Hello,

We did not have the version of this cookbook pinned and when our CI/CD server picked up the new version we began seeing failures.  Our network uses a proxy for all communication.  `http_proxy`, `https_proxy`, and `no_proxy` env vars are set on our AMI running this cookbook.  Our `no_proxy` env var contains the address 169.254.169.254 which is referenced in this block https://github.com/adamsb6/s3_file/blob/master/providers/default.rb#L21.

In version 2.7, that block returns our IAM instance profile name.  In version 2.81, it returns a 503 error because it seems it's recognizing our `http_proxy` and `https_proxy` env vars, but not our `no_proxy` env var.  

In testing, if I set `http_proxy` and `https_proxy` to empty string while maintaining `no_proxy` the cookbook successfully retrieves IAM profile.  If I add this line https://github.com/adamsb6/s3_file/pull/90/files#diff-b047e9d7cf00f238ea53df624dcd96c8L219 back to `libraries/s3_file.rb` in the `def self.client` block, functionality is restored.  

I didn't specifically see anything that would affect this functionality in the code updates but I didn't exhaustively analyze either.  Any help or suggestions would be appreciated.  We currently pinned version to 2.7 as a workaround.  

Thanks!

**Comment by mmkonrad** [comment]
Hello!
Today we experienced the same issue. We are sitting behind a proxy and were also getting a 503 response.
Pinning the version to 2.7 worked as well.
Thank you to @ChrisPetr0 for suggesting to pin the version and the correct version number.

Marcus

**Comment by joekiller** [comment]
It looks like rest-client does use Ruby's underlying URI client which had no_proxy support added so I think adding the line back is correct.

https://github.com/rest-client/rest-client/blob/4ba9f7ee6374ec25abb870f769059b162ad7642a/lib/restclient/request.rb#L434

https://ruby-doc.org/stdlib-2.3.1/libdoc/uri/rdoc/URI/Generic.html#method-i-find_proxy

http://docs.aws.amazon.com/cli/latest/userguide/cli-http-proxy.html
