### ISSUE TITLE
Unable to download package using s3_file

### ISSUE THREAD

**Issue by AnanthRavi** [adamsb6/s3_file#44]
> (php::default line 21) had an error: NoMethodError: undefined method `response' for #<OpenSSL::SSL::SSLError:0x000000080825c0>
> /var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:56:in`rescue in block in get_from_s3'
> /var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:51:in `block in get_from_s3'
> /var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:50:in`each'
> /var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:50:in `get_from_s3'
> /var/chef/cache/cookbooks/s3_file/providers/default.rb:66:in`block in class_from_file'
> /opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
> /opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in`recipe_eval_with_update_check'
> /opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
> /opt/chef/embedded/apps/chef/lib/chef/provider.rb:149:in`run_action'
> /opt/chef/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
> /opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in`run_action'
> /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
> /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in`each'
> /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
> /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in`block in execute_each_resource'
> /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
> /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in`call_iterator_block'
> /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
> /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in`iterate'
> /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
> /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in`execute_each_resource'
> /opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
> /opt/chef/embedded/apps/chef/lib/chef/client.rb:315:in`converge'
> /opt/chef/embedded/apps/chef/lib/chef/client.rb:400:in `block in run'
> /opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in`catch'
> /opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `run'
> /opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in`block in fork_chef_client'
> /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
> /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in`fork_chef_client'
> /opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
> /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in`with_server_connectivity'
> /opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
> /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:355:in`block in interval_run_chef_client'
> /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:345:in `loop'
> /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:345:in`interval_run_chef_client'
> /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:335:in `run_application'
> /opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in`run'
> /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
> /usr/bin/chef-client:40:in`load'

**Comment by AnanthRavi** [comment]
The s3_file cookbook works locally (on vagrant using chef-solo), but doesn't work on ec2 when I use knife to bootstrap a node.

**Comment by joekiller** [comment]
What's your chef version?

**Comment by AnanthRavi** [comment]
I use chef version 12

**Comment by ollielawson** [comment]
I have a very similar error. The cookbook worked fine on Chef 11 but 12 gives me:

================================================================================
    Error executing action `create` on resource 's3_file[/tmp/.ssh/id_rsa]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `response' for #<OpenSSL::SSL::SSLError:0x00000004953860>

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:56:in `rescue in block in get_from_s3'
    /var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:51:in `block in get_from_s3'
    /var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:50:in `each'
    /var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:50:in `get_from_s3'
    /var/chef/cache/cookbooks/s3_file/providers/default.rb:66:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/3sc/recipes/api.rb

     28: s3_file "/tmp/.ssh/id_rsa" do
     29:   remote_path "/chef/ssh/#{ssh_key_name}"
     30:   bucket "secure.3sidedcube.com"
     31:   aws_access_key_id node['aws']['access_key']
     32:   aws_secret_access_key node['aws']['secret_key']
     33:   mode "0644"
     34:   action :create
     35: end
     36:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/3sc/recipes/api.rb:28:in `from_file'

    s3_file("/tmp/.ssh/id_rsa") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :s3_file
      cookbook_name "3sc"
      recipe_name "api"
      remote_path "/chef/ssh/key"
      bucket "****"
      aws_access_key_id "******"
      aws_secret_access_key "*******"
      mode "0644"
      path "/tmp/.ssh/id_rsa"
    end

**Comment by pghalliday** [comment]
Just ran into this issue also on Chef 12.0.3

**Comment by joekiller** [comment]
Anyone still having this issue?

**Comment by pghalliday** [comment]
Haven't tried as I implemented a simple resource using remote_file to work around this

**Comment by AnanthRavi** [comment]
I'm having the same issue as @ollielawson, are you guys planning to push a fix any time soon?

**Comment by joekiller** [comment]
Unfortunately I am unable to replicate the issue so I'm kind of at y'alls
word for how we need to fix it or what the underlying issue is.

**Comment by isaacm** [comment]
Are the issues described above related to #45 ?

**Comment by ollielawson** [comment]
That would make sense as my bucket names have dots/periods in them

**Comment by groboclown** [comment]
I altered the libraries/s3_file.rb file to report the whole error that was caught:

```
          Chef::Log.warn "#{e.backtrace.first}: #{e.message} (#{e.class})" + e.backtrace.drop(1).map{|s| "\t#{s}"}.join("\n")
```

It reports:
```
C:/opscode/chef/embedded/lib/ruby/2.0.0/uri/generic.rb:1203:in `rescue in merge': bad argument (expected URI object or URI string) (ArgumentError)
	C:/opscode/chef/embedded/lib/ruby/2.0.0/uri/generic.rb:1200:in `merge'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rest-client-1.7.3/lib/restclient/abstract_response.rb:66:in `follow_redirection'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rest-client-1.7.3/lib/restclient/abstract_response.rb:41:in `return!'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rest-client-1.7.3/lib/restclient/request.rb:495:in `process_result'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rest-client-1.7.3/lib/restclient/request.rb:421:in `block in transmit'
	C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:852:in `start'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rest-client-1.7.3/lib/restclient/request.rb:413:in `transmit'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rest-client-1.7.3/lib/restclient/request.rb:176:in `execute'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `execute'
	c:/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:52:in `block in get_from_s3'
	c:/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:50:in `each'
	c:/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:50:in `get_from_s3'
	c:/chef/cache/cookbooks/s3_file/providers/default.rb:65:in `block in class_from_file'
```

Looks like the `headers[:location]` response isn't being parsed as a valid url.

**Comment by joekiller** [comment]
Thanks!  That'll help track it down better.

**Comment by AnanthRavi** [comment]
I was previously using a bucket name that had dots like xxx.yyy.com and I replaced that with a bucket that had no special characters and that seems to fix the issue.

**Comment by pghalliday** [comment]
I too was using a bucket with dots. I didn't try one without dots

**Comment by groboclown** [comment]
I've been tracking down this issue a bit.  As far as I can tell, Amazon has stopped support for the path style uris - they only support `(bucketname).s3.amazonaws.com/(path)`.  If you try `s3.amazonaws.com/(bucketname)/(path)`, they send a 301 permanent redirect, but the header does not contain a redirect location; also, the error message body of the returned error indicates that you need to use the `(bucketname).s3.amazonaws.com` format.

Unless I'm mistaken, or unless there's an alternate approach that I haven't found yet, this means that Amazon doesn't support REST services over https for s3 anymore.  As most of you may be aware, putting a bucket name with dots in the name at the start will cause a certificate failure.

**Comment by joekiller** [comment]
Yeah looks like we need to use the rest endpoint for https support:
http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html#WebsiteRestEndpointDiff

**Comment by eric-tucker** [comment]
Just throwing in that I just got this error downloading from an S3 bucket:

```
  * s3_file[/tmp/logos.tgz] action create
    
    ================================================================================
    Error executing action `create` on resource 's3_file[/tmp/logos.tgz]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `response' for #<OpenSSL::SSL::SSLError:0x0000000531c1a8>
    
    Cookbook Trace:
    ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/s3_file/libraries/s3_file.rb:56:in `rescue in block in get_from_s3'
    /etc/chef/local-mode-cache/cache/cookbooks/s3_file/libraries/s3_file.rb:51:in `block in get_from_s3'
    /etc/chef/local-mode-cache/cache/cookbooks/s3_file/libraries/s3_file.rb:50:in `each'
    /etc/chef/local-mode-cache/cache/cookbooks/s3_file/libraries/s3_file.rb:50:in `get_from_s3'
    /etc/chef/local-mode-cache/cache/cookbooks/s3_file/providers/default.rb:65:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/mycookbook/recipes/batch_server.rb

     13: s3_file "/tmp/logos.tgz" do
     14:   bucket "my-bucket"
     15:   remote_path "logos.tgz"
     16:   only_if { Dir["/var/www/_logo/*"].empty? }
     17: end
     18:

    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/mycookbook/recipes/batch_server.rb:13:in `from_file'

    s3_file("/tmp/logos.tgz") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :s3_file
      cookbook_name "mycookbook"
      recipe_name "batch_server"
      bucket "my-bucket"
      remote_path "logos.tgz"
      path "/tmp/logos.tgz"
      only_if { #code block }
    end
```

**Comment by joekiller** [comment]
@eric-tucker What version of chef are you running?

**Comment by eric-tucker** [comment]
12.3.0

**Comment by joekiller** [comment]
Please reopen if it this still happens.
