### ISSUE TITLE
Support for periods in bucket names

### ISSUE THREAD

**Issue by groboclown** [adamsb6/s3_file#45]
If a bucket name has a period in it (such as "abc.test"), the generated url is `https://abc.test.s3.amazonws.com/blah`.  However, this results in an invalid certificate, because the server names no longer match.  Amazon has support for a "path" flavor of urls, which are in the form `https://s3.amazonws.com/abc.test/blah`, however that seems to cause an invalid URL parsing error from the rest-client gem.

**Comment by eherot** [comment]
@groboclown are you saying that you're getting a rest-client error when trying to specify the `s3_url` parameter as a workaround for accessing bucket names with dots? The latter URL you specified *should* work (and did when I submitted https://github.com/adamsb6/s3_file/pull/31)

**Comment by groboclown** [comment]
Looks like I was using an older version that didn't support the "s3_url" parameter.  Thanks for pointing out the new feature!
