### ISSUE TITLE
Specify dependency version on rest-client

### ISSUE THREAD

**Issue by tunylund** [adamsb6/s3_file#46]
Hi,

We bumbed into an issue where the very latest rest-client failed to install on our vagrant-box. The issue was fixable by downgrading the rest-client dependency into 1.7.3 instead of 'latest'. I'm not sure if this is specific to just our vagrant-box which is running ubuntu 12, but you might anyway want to consider dealing with the dependencies in managed way instead of trusting the 'latest'.

https://github.com/adamsb6/s3_file/blob/master/recipes/dependencies.rb#L2

**Comment by mrjackdavis** [comment]
+1

**Comment by kmkswamy** [comment]
i am facing the same with centos6.6 vagrant also.

**Comment by CrossTheStreams** [comment]
:+1:

**Comment by tunylund** [comment]
Just to clarify, the "correct" way to fix the issue with our vagrant-box is to make the rest-client install properly. The issue with s3_file, that i'm raising is that by depending on no particular version of rest-client, the users of s3_file are subject to unnecessary surprises as rest-client changes occur on their own accord.

**Comment by joekiller** [comment]
Yeah we should pin this.  PRs welcome

**Comment by ge1st** [comment]
Sorry for the double submit. Had to rewrite some metadata in the commit.
