### ISSUE TITLE
s3_file fails to load instance profile when ENV['http_proxy'] is set.

### ISSUE THREAD

**Issue by grosendorf** [adamsb6/s3_file#49]
When http_proxy is set in a node's client.rb, the s3_file provider fails to load the instance profile. It instead loads the proxy's instance profile (if it exists), otherwise is raises the following ArgumentError
`No credentials provided and no instance profile on this machine.`

**Comment by vigith** [comment]
looks like it doesn't respond no_proxy

I made the following change in `s3_file/libraries/s3_file.rb`

```
@@ -140,6 +140,8 @@
   def self.client
     require 'rest-client'
     RestClient.proxy = ENV['http_proxy']
+    RestClient.proxy = ENV['https_proxy']
+    RestClient.proxy = ENV['no_proxy']
     RestClient
   end
```

**Comment by joekiller** [comment]
thanks for reporting this

**Comment by joekiller** [comment]
fix is live
