### ISSUE TITLE
Doesn't work for eu-central-1 S3 buckets

### ISSUE THREAD

**Issue by DaKoTTS** [adamsb6/s3_file#52]
I am getting a "400" for the s3 Buckets in eu-central. I think this is because of the new AWS Sigv4!
A request looks like that:
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>...</RequestId><HostId>...</HostId></Error>

From aws side:
I have been in touch with the SDK and the S3 service team.
The S3 team confirmed the behavior is expected as the signature Sigv4 is being rolled out (S3 and other services).
Here are the main benefits between Sigv4 over Sigv2
  - Increased security
  - Improved performances
  - Support for larger API call payload
  - Further isolate regions for better security

It's also worth noting that the Sigv4 will be the preferred method in the future.

Somebody has allready a fix for that problem? Would be wonderfull :)

**Comment by joekiller** [comment]
@DaKoTTS this update was pushed.
