### ISSUE TITLE
RestClient::Forbidden: 403 Forbidden  while get data from S3

### ISSUE THREAD

**Issue by johnqu112** [adamsb6/s3_file#53]
I am using s3_file cookbook 2.5.4 to test retrieving data from Amazon govClound S3 site. I got 403 error. Here is chef-client run console output information:

The data file has permission for public access, I can access the file using the browser. I read a prior posting on the same issue, the recommended solution was to remove the s3_url. But this would not work for my case ( since I try to access AWS govclound, not default AWS). What would be the problem this time? I would appreciate a solution.

----------------------------------------
    s3_file("c:\temp\locals3datafile.txt") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :s3_file
      cookbook_name "winhello"
      recipe_name "s3get"
      remote_path "S3testdatafile.txt"
      bucket "mitre-cocreate-win-test"
      aws_access_key_id "XXXX"
      aws_secret_access_key "ZZZZ"
      s3_url "https://s3-us-gov-west-1.amazonaws.com"
      path "c:\\temp\\locals3datafile.txt"
    end

[2015-09-03T17:04:16+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2015-09-03T17:04:16+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-09-03T17:04:16+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 19.572001 seconds
[warning] The response contained in an RestClient::Exception is now a RestClient::Response instead of a Net::HTTPRespons
e, please update your code
[2015-09-03T17:04:16+00:00] INFO: Sending resource update report (run-id: c384f877-7b46-4616-bcbe-cb6274534de2)
[2015-09-03T17:04:16+00:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2015-09-03T17:04:16+00:00] FATAL: RestClient::Forbidden: 403 Forbidden

**Comment by eherot** [comment]
@johnqu112 this is kind of a guess but have you tried appending the bucket name to the end of the S3 URL?

**Comment by eherot** [comment]
You might also have to leave the `bucket` option out of the resource call for it to work.

**Comment by joekiller** [comment]
@eherot is correct in that you need to drop bucket and do 

```
  s3_url "https://s3-us-gov-west-1.amazonaws.com/mitre-cocreate-win-test"

```

**Comment by patcon** [comment]
Just an added note, but it also seems to fail if the s3_url ends in a slash

**Comment by ngtjah** [comment]
I had a similar problem. This fixed it for me. Is this patch going to be included in the main cookbook soon?

https://github.com/TaopaiC/aws

**Comment by joekiller** [comment]
@ngtjah what fixed your problem?

**Comment by ngtjah** [comment]
sorry I got my problems mixed up actually. 

My 403 Forbidden problems were related to the time not being set properly on my system because the timestamp is sent in the URL to amazon...

I could see this by taking this URL and placing it in the browser.

```
[2015-11-03T11:06:35-06:00] WARN: remote_file[/home/nfs-prompts.tar.gz] cannot be downloaded from https://xxxxxxxxxxxxx.s3-us-west-1.amazonaws.com/nfs-prompts.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AXXXXXXXXXXXXX%2F20151103%2Fus-west-1%2Fs3%2Faws4_request&X-Amz-Date=20151103T170635Z&X-ders=host&X-Amz-Signature=3ac3a3ea2563bac2b2e629f2d7d93f60e676e798axxxxxxxxxxxxxxxxx: 403 "Forbidden"
```

If you get a 403 make sure you have synced time.

**Comment by joekiller** [comment]
Pretty sure this can be closed. Please reopen and give more details if now.

**Comment by jerroydmoore** [comment]
Do you suppose if s3_file fails, we could see the body of the response? An expired request could lead developers to check their time.

I've also been getting 403s, and didn't think to check to see if my time is sync'ed.
