### ISSUE TITLE
Running in newest opsworks fails because of rest-client

### ISSUE THREAD

**Issue by felipejfc** [adamsb6/s3_file#58]
## LoadError

cannot load such file -- rest-client
## Cookbook Trace:

/var/chef/runs/f7e1edcd-f360-43cd-bf46-9c72bb601dd3/local-mode-cache/cache/cookbooks/s3_file/libraries/s3_file.rb:209:in `client'
/var/chef/runs/f7e1edcd-f360-43cd-bf46-9c72bb601dd3/local-mode-cache/cache/cookbooks/s3_file/providers/default.rb:8:in`block in class_from_file'
#### EDIT

Using older version (2.5.2) worked.

**Comment by workeitel** [comment]
Which version have you used before (you mention that 2.5.2 works)? your rest-client gem got not installed. This should be done since https://github.com/adamsb6/s3_file/commit/aaf55d9997b2934a7a8dade16b1eb9202c628f6e automatically via the included `include_recipe 's3_file::dependencies'`

**Comment by felipejfc** [comment]
before I was using latest version (2.6.5)

**Comment by flah00** [comment]
I was also having issues with 2.6.5, when creating dynamic resources. It seems that `include_recipe` does not work as expected, with dynamic resources. I worked around the issue, by including the `s3_file::dependencies` recipe before the recipe which dynamically creates my `s3_file` resource.

**Comment by felipejfc** [comment]
thanks for the workaround for using the latest version @flah00, I'll do it as well while no fix is made.

**Comment by joekiller** [comment]
Thanks for the report.

**Comment by joekiller** [comment]
@felipejfc can you try version 2.6.2?

**Comment by patcon** [comment]
Hey @joekiller! I had the same issue on 2.6.5, and knew that it had been working on 2.5.4. I tried 2.6.2 like you suggested, and it appears the the recipe is now installed :)

thanks!

**Comment by felipejfc** [comment]
@joekiller I also had success with 2.6.2 :)

**Comment by bmhatfield** [comment]
I commented in this closed PR first: https://github.com/adamsb6/s3_file/pull/57 before noticing this issue. PR #57 is the cause of this, as it switches from `compile_time true` (the default) to `compile_time false`, which breaks it.

**Comment by joekiller** [comment]
I updated it to compile_time true. Try version 2.6.6 (latest)
