### ISSUE TITLE
407 "Proxy Authentication Required"

### ISSUE THREAD

**Issue by in4mer** [adamsb6/s3_file#85]
This works with 2.5.2, does not work with 2.7.0.  This uses a network-local proxy that requires user:pass authentication to accept requests.

Generated at 2016-06-23 00:53:34 +0000
Net::HTTPServerException: s3_file[/var/chef/cache/simpledata-build.tgz](simpledata::default line 201) had an error: Net::HTTPServerException: 407 "Proxy Authentication Required"
/opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
/opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:128:in`value'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:915:in `connect'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:863:in`do_start'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in`transmit'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in`execute'
/var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:101:in `block in do_request'
/var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:78:in`with_region_detect'
/var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:92:in `do_request'
/var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:124:in`get_digests_from_s3'
/var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:120:in `get_md5_from_s3'
/var/chef/cache/cookbooks/s3_file/providers/default.rb:39:in`block in class_from_file'
(eval):2:in `block in action_create'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider.rb:360:in`instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider.rb:360:in `compile_and_converge_action'
(eval):2:in`action_create'

**Comment by joekiller** [comment]
Please reopen if this still happens.
