### ISSUE TITLE
Win32APIError: when running on windows 2012 

### ISSUE THREAD

**Issue by stairsdba** [adamsb6/s3_file#86]
Cookbook version

2.7.0
Chef-client version

12.2
Platform Details

AWS OpsWorks, windows 2012 r2
Scenario:

Save a file from S3 to a local directory
Steps to Reproduce:

s3_file 'c:\temp\file.txt' do
bucket "bucketname"
aws_access_key_id "key"
aws_secret_access_key "secret"
remote_path "file.txt"
action :create
end

If I comment out the following lines in providers\default.rb it will work

f = file new_resource.path do
action :create
# owner new_resource.owner || ENV['user']
# group new_resource.group || ENV['user']
# mode new_resource.mode || '0644'

end
Expected Result:

file to be created
Actual Result:

Exception

[2016-08-24T12:59:01+00:00] ERROR: Running exception handlers
[2016-08-24T12:59:01+00:00] ERROR: Exception handlers complete
[2016-08-24T12:59:01+00:00] FATAL: Stacktrace dumped to c:/chef/runs/21611189-5920-4dc1-94e0-dbd04dca3068/local-mode-cache/cache/chef-stacktrace.out
[2016-08-24T12:59:01+00:00] FATAL: Chef::Exceptions::Win32APIError: s3_filec:\temp\Director.properties had an error: Chef::Exceptions::Win32APIError: filec:\temp\Director.properties had an error: Chef::Exceptions::Win32APIError: No mapping between account names and security IDs was done.
---- Begin Win32 API output ----
System Error Code: 1332
System Error Message: No mapping between account names and security IDs was done.
---- End Win32 API output ----

**Comment by phundisk** [comment]
I received the same message.  Does this cookbook support Windows?

**Comment by pbergstedt** [comment]
Same error on 2012R2 with s3_file v2.7.0, with chef client v12.15.19 only during the bootstrap run.  If I run the recipe from a command (as Administrator) it works without any modification to the provider.

**Comment by joekiller** [comment]
Seems like you need permissions. Not an issue?

Please reopen if this still happens.

**Comment by lochnesh** [comment]
Our team encountered this issue on Windows 2012 R2.  The solution we found was to set `owner` and `group` to a user who was defined on the box.  

```
s3_file 'c:\temp\file.txt' do
  bucket "bucketname"
  aws_access_key_id "key"
  aws_secret_access_key "secret"
  remote_path "file.txt"
  owner some-windows-user
  group some-windows-user
  action :create
end
```

**Comment by pkazi** [comment]
Faced same issue and happens only when chef-client is run on machine bootstrap and run from task scheduler as SYSTEM user account.
