### ISSUE TITLE
Bump version for supermarket release

### ISSUE THREAD

**Issue by frank-m** [adamsb6/s3_file#92]
Hi,

Would ie be possible to do a new supermarket release with a higher version?

That way we can freeze the cookbooks on our end.

Cheers,

Frank

**Comment by jakauppila** [comment]
Can this be completed? We need #90 in a release as the cookbook is currently broken when the `no_proxy` environment variable is defined.

**Comment by joekiller** [comment]
v2.8.0 is released.
